"use client";
import {useEffect,useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {driverIncidentAction} from "@/app/route-exception-actions";
export function RouteExceptionControls({route,leg,incident,closed}:{route:string;leg:string;incident?:{id:string;status:string;deadline:string}|null;closed:boolean}){
 const [pending,start]=useTransition();const [error,setError]=useState('');const [left,setLeft]=useState(900);const router=useRouter();
 const act=(outcome?:string)=>start(async()=>{setError('');const result=await driverIncidentAction(outcome?incident!.id:route,outcome);if(result.error)setError(result.error);else router.refresh();});
 useEffect(()=>{if(incident?.status!=='Open')return;let submitted=false;const tick=()=>{const remaining=Math.max(0,Math.ceil((Date.parse(incident.deadline)-Date.now())/1000));setLeft(remaining);if(!remaining&&!submitted){submitted=true;void driverIncidentAction(incident.id,'Rescheduled').then(result=>{if(result.error)setError(result.error);router.refresh();}).catch(()=>setError('Could not confirm timeout; the scheduled worker will retry.'));}};tick();const timer=setInterval(tick,1000);return()=>clearInterval(timer);},[incident?.id,incident?.status,incident?.deadline,router]);
 return <section className="driver-card pickup-controls"><h2>Route exceptions</h2>{!incident&&!closed&&<button className="secondary" disabled={pending} onClick={()=>{if(window.confirm('Report driver unavailable and notify remaining customers?'))act();}}>Driver unavailable · notify customers</button>}{incident?.status==='Open'&&<><p className="notice error">Route paused. Confirm within {Math.floor(left/60)}:{String(left%60).padStart(2,'0')}. Without confirmation, the next route day is booked with $10 refund terms per job.</p><button disabled={pending||left===0} onClick={()=>act('Continued')}>Replacement available · continue (~1 hour)</button><button className="secondary" disabled={pending} onClick={()=>act('Rescheduled')}>Reschedule next {leg==='Pickup'?'Pickup route day':'delivery route day'} · $10 refund due</button><button className="secondary" disabled={pending||left===0} onClick={()=>act('NoDriver')}>No replacement · {leg==='Pickup'?'reschedule Pickup':'free shop pickup'} · $10 refund due</button></>}{incident&&incident.status!=='Open'&&<p className="notice">{incident.status==='Continued'?'Replacement confirmed. Customers can wait (~1 hour, $5 refund due) or reschedule.':incident.status==='Rescheduled'?`Customers rescheduled to the next available ${leg==='Pickup'?'Pickup route day':'delivery route day'}. $10 refund due per job.`:leg==='Pickup'?'No replacement. Pickup rescheduled free of charge; $10 refund due.':'No replacement. Free shop pickup; $10 refund due.'} Refunds are complete only when actually issued.</p>}{error&&<p role="alert" className="notice error">{error}</p>}</section>;
}
